<a href="https://colab.research.google.com/github/kiryu-3/Prmn2024_mng/blob/main/Python/Streamlit/Streamlit_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Streamlit

In [ ]:
# 最初に実行してください
# ライブラリのインストール
!pip install Streamlit
!pip install yfinance

In [ ]:
# 最初に実行してください
# モジュールのインポート
import streamlit as st
import requests

## Streamlitとは

[**Streamlit**](https://streamlit.io/)は、Pythonのライブラリであり、Webアプリケーションを簡単に作成するためのフレームワークです。  
PythonでWebアプリを開発する際には、通常[**Flask**](https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/index.html)や[**Django**](https://docs.djangoproject.com/ja/4.1/)などのライブラリが使用されますが、  
これらを学ぶにはHTML、CSS、JavaScriptなどのフロントエンドの知識が必要です。

しかし、Streamlitを利用すれば、非常に迅速かつ容易に動作するアプリケーションを構築できます。  
主にデータサイエンス分野で利用され、データの可視化や解析に役立ちます。

Streamlitは、シンプルで直感的なインターフェースを提供することが特徴であり、細かな設定を行う必要はありません。  
そのため、プロトタイピングや素早い実験に適しています。


本教材は、以下のページを参考にして作成されました：[こちら](https://data-analytics.fun/2022/08/28/streamlit-recap/#toc10)。

## Streamlitの基本的な使い方(Colab版)

GoogleColabにおけるStreamlitの実行方法は、以下のステップに従います。

1. pyファイルにコードを記述する
2. pyファイルをstreamlitコマンドで実行
3. 公開されたURLにアクセス

1. pyファイルにコードを記述する

``` python
# sample.pyというファイルに記述する

%%writefile sample.py
import streamlit as st

# コードとその実行結果を上下に表示する
st.code("st.title(\"Streamlit入門\")")
st.title("Streamlit入門")
```

2. pyファイルをstreamlitコマンドで実行

- `your globalip`に続くアドレスがIPアドレス。入力を求められることがある。
- `your url is`に続くURLにアクセスする。例の場合はhttps://sample.loca.lt

``` python
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

```

![](https://imgur.com/LDNnALw.png)

3. 公開されたURLにアクセス

- 「click to Submit」となっているところからアクセスする。
- IPアドレスの入力を求められることがある。

![](https://imgur.com/m0etUlz.png)

In [ ]:
#@title Streamlitの基本的な使い方(Colab版)
# sample.pyというファイルに記述する

%%writefile sample.py
import streamlit as st

# タイトルを表示
st.title("Streamlit入門")

Overwriting sample.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

your globalip: 34.145.35.217

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.12:8501
  External URL: http://34.145.35.217:8501

npx: installed 22 in 1.608s
your url is: https://sample.loca.lt
  Stopping...
^C

![リンクテキスト](https://imgur.com/cb9AiMP.png)

## テキストの表示

参考ページ：[こちら](https://data-analytics.fun/2022/01/29/understanding-streamlit-1/#i)

- `st.title()`：タイトルを表示
- `st.header()`：ヘッダーを表示
- `st.subheader()`：サブヘッダーを表示
- `st.text()`：純粋なテキストを表示
- `st.caption()`：キャプションを表示
- `st.markdown()`：Markdownを表示
- `st.code()`：プログラムコードを表示
  - 引数一つ目は表示したいコード。
  - 引数二つ目はプログラミング言語。デフォルトは"Python"。
- `st.latex()`：Texを表示
  - "Tex"：数式を綺麗に書くことができる表記法。

In [ ]:
#@title テキストの表示
# sample2.pyというファイルに記述する

%%writefile sample2.py
import streamlit as st

# タイトルを表示
st.title("タイトルを表示")

# ヘッダーを表示
st.header("ヘッダーを表示")

# サブヘッダーを表示
st.subheader("サブヘッダーを表示")

# 純粋なテキストを表示
st.text("テキストを表示")

# キャプションを表示
st.caption("キャプションを表示")

Overwriting sample2.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample2.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample2.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

以下のように表示されます。

![](https://imgur.com/cahrOBs.png)

In [ ]:
# sample3.pyというファイルに記述する

%%writefile sample3.py
import streamlit as st

markdown = """
### pythonによるHello, world!
``` py
print("Hello, world!")
````
"""

code = """
#include <stdio.h>

int main() {
    printf("Hello, world!\\n");
    return 0;
}
"""

# markdownを表示
st.markdown(markdown)

# プログラムコードを表示
st.subheader("C言語によるHello, world!")
st.code(code, language="c")

# 数式を表示
st.subheader("運動方程式")
st.latex("M\ddot{x}=F")

Writing sample3.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample3.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample3.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

以下のように表示されます。

![](https://imgur.com/kp1OZ7p.png)

## 表の表示

参考ページ：[こちら](https://data-analytics.fun/2022/01/29/understanding-streamlit-1/#i-2)


- `st.dataframe()`：インタラクティブな表を表示
  - pandasのデータフレームを引数として渡す。
  - 引数`width`と`height`で幅と高さを調整することができる。
- `st.table()`：静的な表を表示
  - pandasのデータフレームを引数として渡す。

ここでは、現在年のGAFAMの株価の時系列情報を取得します。
（参考にしたサイトは[こちら](https://toukei-lab.com/python_stock)）

- G：**Google**のこと。親会社は**Alphabet**。
- A：**Apple**のこと。
- F：**Facebook**のこと。2021年に社名を**Meta**に変更している。
- A：**Amazon**のこと。
- M：Microsoftのこと。

`datatime`モジュールを使って、本日の日付までの株価を確認します。
（3日ほどずれると思います）

In [ ]:
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 現在の年の1月1日を取得
start_date = datetime(datetime.today().year, 1, 1).strftime('%Y-%m-%d')
# 取得終了日を現在日時にする（UTC+9時間で指定）
end_date = (datetime.today() + timedelta(hours=9)).strftime('%Y-%m-%d')

# Google、Apple、Facebook、Amazonの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# DataFrameの表示
df.iloc[-8:-1]

[*********************100%%**********************]  5 of 5 completed

                Google       Apple    Facebook      Amazon   Microsoft
Date
2024-02-13  145.139999  185.039993  460.119995  168.639999  406.320007
2024-02-14  145.940002  184.149994  473.279999  170.979996  409.489990
2024-02-15  142.770004  183.860001  484.029999  169.800003  406.559998
2024-02-16  140.520004  182.309998  473.320007  169.509995  404.059998
2024-02-20  141.119995  181.559998  471.750000  167.080002  402.790009
2024-02-21  142.550003  182.320007  468.029999  168.589996  402.179993
2024-02-22  144.089996  184.369995  486.130005  174.580002  411.649994

このデータフレームを表示してみます。

In [ ]:
#@title 表の表示
# sample4.pyというファイルに記述する

%%writefile sample4.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 現在の年の1月1日を取得
start_date = datetime(datetime.today().year, 1, 1).strftime('%Y-%m-%d')
# 取得終了日を現在日時にする（UTC+9時間で指定）
end_date = (datetime.today() + timedelta(hours=9)).strftime('%Y-%m-%d')

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# インタラクティブな表を表示
st.subheader("インタラクティブな表を表示")
st.dataframe(df, width=None, height=500)

# 静的な表を表示
st.subheader("静的な表を表示")
st.table(df.iloc[-8:-1])

Overwriting sample4.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample4.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample4.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

以下のように表示されます。

![](https://imgur.com/rul1LkW.png)

![](https://imgur.com/1EKluUz.png)

## なんでも表示

`st.write()`とすると、形式を渡されたデータに自動で合わせて出力してくれます。

通常の文字列、Markdown、DataFrame、何でもOKです。

In [ ]:
#@title なんでも表示
# sample5.pyというファイルに記述する

%%writefile sample5.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 現在の年の1月1日を取得
start_date = datetime(datetime.today().year, 1, 1).strftime('%Y-%m-%d')
# 取得終了日を現在日時にする（UTC+9時間で指定）
end_date = (datetime.today() + timedelta(hours=9)).strftime('%Y-%m-%d')

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# `st.write()`による表の表示
st.subheader("`st.write()`で表を表示")
st.write(df)

Writing sample5.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample5.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample5.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

以下のように表示されます。  
`st.dataframe()`と`st.table()`と比較すると少し表示が異なります。

![](https://imgur.com/BPMpJAL.png)

## 指標の表示・分割表示

参考ページ：[こちら](https://data-analytics.fun/2022/01/29/understanding-streamlit-1/#i-2)

- `st.metric()` ：指標を表示
  - `label`：数値の説明
  - `value`：表示する数値
  - `delta`：直前の値との差分（省略可能）
  - `delta_color`：

    -   `normal`：プラスであれば緑色、マイナスであれば赤色
    -   `reverse`：normalの逆
    -   `off`：色を変えない
- `st.columns()` ：列を分割する
  - 引数で分割する個数を指定できる

本日の日付までの5社の株価を確認します。
（3日ほどずれると思います）

In [ ]:
#@title 指標の表示・分割表示
# sample5.pyというファイルに記述する

%%writefile sample5.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 現在の年の1月1日を取得
start_date = datetime(datetime.today().year, 1, 1).strftime('%Y-%m-%d')
# 取得終了日を現在日時にする（UTC+9時間で指定）
end_date = (datetime.today() + timedelta(hours=9)).strftime('%Y-%m-%d')

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# 5社の株価
names = ["Google", "Apple", "Facebook", "Amazon", "Microsoft"]

st.subheader(f'{end_date.replace("-", "/")}の株価')
cols = st.columns(len(names))
for name, col in zip(names, cols):
    value = round(df.iloc[-1][name], 1)
    delta = round(df.iloc[-1][name] - df.iloc[-2][name], 1)
    col.metric(label=name, value=f'${value}', delta=f'{delta}')

Overwriting sample5.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample6.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample6.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

  Stopping...
^C

以下のように表示されます。
（日時は多少ズレがあると思います）

![](https://imgur.com/s8h6uCI.png)

## グラフの表示

参考ページ：[こちら](https://data-analytics.fun/2022/01/29/understanding-streamlit-1/#i-3)

- `st.line_chart()` ：折れ線グラフを表示
- `st.area_chart()` ：エリアチャートを表示
- `st.bar_chart()` ：棒グラフを表示
  - 引数`width`と`height`で幅と高さを調整することができる。
  - 引数`use_container_width`を`True`とすると、画像を列のサイズに自動的に合わせる。

In [ ]:
#@title グラフの表示①
# sample7.pyというファイルに記述する

%%writefile sample7.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 現在の年の1月1日を取得
start_date = datetime(datetime.today().year, 1, 1).strftime('%Y-%m-%d')
# 取得終了日を現在日時にする（UTC+9時間で指定）
end_date = (datetime.today() + timedelta(hours=9)).strftime('%Y-%m-%d')

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# 現在年の株価推移（線グラフ）
st.subheader(f"{datetime.today().year}年の株価推移（線グラフ）")
st.line_chart(df)

# 2023年の株価推移（エリアグラフ）
st.subheader(f"{datetime.today().year}年の株価推移（エリアグラフ）")
st.area_chart(df)

# 2023年の株価変化率の比較
# リターンの計算
df_return = df.apply(lambda x: (x[-1] - x[0]) / x[0], axis=0)
st.subheader(f"{datetime.today().year}年の株価変化率の比較")
st.bar_chart(df_return)

Writing sample7.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample7.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample7.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

以下のように表示されます。

![](https://imgur.com/Sykdio8.png)

![](https://imgur.com/Xn3YzTy.png)

![](https://imgur.com/fiVwpvi.png)

ライブラリ**Matplotlib**でグラフを作成し、それをstreamlitで表示することができます。  
`st.pyplot()`を使います。

今までのグラフよりも細かい設定をすることができるようになります。

さらに、ライブラリ**Plotly**を使うことで、インタラクティブなグラフを作成することができます。  
`st.plotly_chart()`を使います。

参考になるページ：[こちら](https://data-analytics.fun/2021/11/19/plotly-summary/)

In [ ]:
#@title グラフの表示②
# sample8.pyというファイルに記述する

%%writefile sample8.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import plotly.graph_objects as go

# 現在の年の1月1日を取得
start_date = datetime(datetime.today().year, 1, 1).strftime('%Y-%m-%d')
# 取得終了日を現在日時にする（UTC+9時間で指定）
end_date = (datetime.today() + timedelta(hours=9)).strftime('%Y-%m-%d')

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# Google、Apple、Facebook、Amazon, Microsoft
names = ["Google", "Apple", "Facebook", "Amazon", "Microsoft"]
# リターンの計算
df_return = df.apply(lambda x: (x[-1] - x[0]) / x[0], axis=0)

# 現在年の株価変化率の比較(matplotlib)
fig, ax = plt.subplots()
ax.bar(x=names, height=df_return[names], color='green', width=0.6, alpha=0.6)
st.subheader(f'{datetime.today().year}年の株価変化率の比較')
st.pyplot(fig)

# 現在年の株価変化率の比較(plotly)
fig = go.Figure()
for company in df.columns:
    fig.add_trace(go.Scatter(x=df.index,
                             y=df[company],
                             mode='lines',
                             name=company,
                             line=dict(width=3))
                 )
fig.update_layout(
    title="現在年の株価変化率の比較",
    plot_bgcolor='white',
    legend=dict(x=1.02, y=1.0, orientation='v'),  # 凡例をグラフの外に配置
    xaxis=dict(tickfont_color='grey', showline=True, linewidth=1, linecolor='lightgrey'),
    yaxis=dict(tickfont_color='grey', showline=True, linewidth=1, linecolor='lightgrey')
)

st.subheader(f'{datetime.today().year}年の株価変化率の比較')
st.plotly_chart(fig)

Overwriting sample8.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample8.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample8.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

以下のように表示されます。

![](https://imgur.com/1OoPZVx.png)

![](https://imgur.com/FAfzwPp.png)

## ウィジェットの表示①

普通にウィジェットを作るとHTML、CSS、JavaScriptなどを何行も書かないといけなくなるようですが、
Streamlitを使うとほんの数行で書くことができて非常に便利です。

参考ページ：[こちら](https://data-analytics.fun/2022/06/26/streamlit-widget-1/)  
公式ページ：[こちら](https://docs.streamlit.io/library/api-reference/widgets)

- `st.button()` ：ボタンを作成
  - `label`プロパティ：表示するラベルを指定できる
``` python
col = st.columns(3)
button_1 = col[0].button(f'{datetime.today().year}年')
button_2 = col[1].button(f'{datetime.today().year - 1}年')
button_3 = col[2].button(f'{datetime.today().year - 2}年')
```
![](https://imgur.com/vfMHmWh.png)

- `st.download_button()` ：ダウンロードボタンを作成

  - `label`：ボタンに対するラベル
  -`data`：ダウンロードするデータ
  -`file_name`：ファイルをダウンロードしたときのファイル名
  -`mine`：ファイルの形式を設定  「`text/csv`」,「`text/plain`」,「`image/png`」などがある
``` python
csv_data = df_1[stocks].to_csv().encode('UTF-8')
st.download_button(
      label='Data Download',
      data=csv_data,
      file_name=f'stockprice_{datetime.today().year}.csv',
      mime='text/csv',
)
```
![](https://imgur.com/tJh2fiu.png)

- `st.checkbox()`：チェックボックスを作成
  - `label`プロパティ：選択肢を指定する
``` python
col = st.columns(5)
    stocks = []
    if col[0].checkbox(label='Google', key='google'):
        stocks.append('Google')
    if col[1].checkbox(label='Apple', key='apple'):
        stocks.append('Apple')
    if col[2].checkbox(label='Facebook', key='facebook'):
        stocks.append('Facebook')
    if col[3].checkbox(label='Amazon', key='amazon'):
        stocks.append('Amazon')
    if col[4].checkbox(label='Microsoft', key='microsoft'):
        stocks.append('Microsoft')
```
![](https://imgur.com/6UY8jYS.png)

- `st.radio()`：ラジオボタンを作成
  - 複数の選択肢の中から一つ選ぶボタンを作成できる。
  - `label`：ラジオボタンの上に表示するテキスト
  - `options`：選択するリスト
  - `index`：デフォルトで選択されている項目
  - `horizontal`：`True`にすると横に並べて表示
``` python
names = ["Google", "Apple", "Facebook", "Amazon", "Microsoft"]
st.radio(
      label='銘柄を選択してください',
      options=names,
      index=0,
      horizontal=True,
)
```
![](https://imgur.com/NYUwPmg.png)

- `st.selectbox()` ：セレクトボックスを作成
  - `label`：セレクトボックスの上に表示するテキスト
  - `options`：選択項目を設定（リスト、Series、indexなど）
``` python
select_modes = ["チェックボックス", "ラジオボタン", "セレクトボックス"]
st.selectbox(
      label="銘柄の選択方法を選んでください",
      options=select_modes,
)
```
![](https://imgur.com/0VoygNm.png)


- `st.multiselect()`：マルチセレクトボックスを作成
  - `label`：セレクトボックスの上に表示するテキスト
  - `options`：選択項目を設定（リスト、Series、indexなど）
  - `default`：指定したラベルが最初から選択された状態になる
``` python
names = ["Google", "Apple", "Facebook", "Amazon", "Microsoft"]
stocks = st.multiselect(
      label="銘柄を選んでください",
      options=names,
      default=["Google", "Apple"]
)
```
![](https://imgur.com/cV5zAF0.png)

In [ ]:
#@title ウィジェットの表示①
# sample9.pyというファイルに記述する

%%writefile sample9.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

def select_mode(mode):
    # Google、Apple、Facebook、Amazon, Microsoft
    names = ["Google", "Apple", "Facebook", "Amazon", "Microsoft"]

    # チェックボックス
    if mode=="チェックボックス":
        col = st.columns(5)
        stocks = []
        if col[0].checkbox(label='Google', key='google'):
            stocks.append('Google')
        if col[1].checkbox(label='Apple', key='apple'):
            stocks.append('Apple')
        if col[2].checkbox(label='Facebook', key='facebook'):
            stocks.append('Facebook')
        if col[3].checkbox(label='Amazon', key='amazon'):
            stocks.append('Amazon')
        if col[4].checkbox(label='Microsoft', key='microsoft'):
            stocks.append('Microsoft')
    elif mode=="ラジオボタン":
        # ラジオボタンで銘柄を選択する
        stocks = st.radio(label='銘柄を選択してください', options=names, index=0, horizontal=True)
    elif mode=="セレクトボックス":
        # セレクトボックスで銘柄を選択する
        stocks = st.multiselect(label="銘柄を選んでください", options=names, default=["Google", "Apple"])
    return stocks

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]

# 過去3年分のデータを取得し、それぞれのデータフレームを作成する
for minus in range(3):
    # 1月1日を取得
    start_date = datetime(datetime.today().year - minus, 1, 1).strftime('%Y-%m-%d')
    # 12月31日を取得
    end_date = datetime(datetime.today().year - minus, 12, 31).strftime('%Y-%m-%d')

    # 株価情報の取得
    price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

    # データフレームの作成
    globals()[f"df_{minus+1}"] = pd.DataFrame({
        "Google": price_data[tickers[0]],
        "Apple": price_data[tickers[1]],
        "Facebook": price_data[tickers[2]],
        "Amazon": price_data[tickers[3]],
        "Microsoft": price_data[tickers[4]]
    })

st.header('株価推移')
# 3つの列を作成
col = st.columns(3)
# 3年分のボタン
button_1 = col[0].button(f'{datetime.today().year}年')
button_2 = col[1].button(f'{datetime.today().year - 1}年')
button_3 = col[2].button(f'{datetime.today().year - 2}年')
# 選択モードのリスト
select_modes = ["チェックボックス", "ラジオボタン", "セレクトボックス"]

# 現在年のボタン
if button_1:
    st.subheader(f'{datetime.today().year}年の株価推移')
    # 選択モードの選択
    mode = st.selectbox(label="銘柄の選択方法を選んでください", options=select_modes)
    # 選択された銘柄の取得
    stocks = select_mode(mode)
    # CSVデータのエンコード
    csv_data = df_1[stocks].to_csv().encode('UTF-8')
    # ダウンロードボタンの表示
    st.download_button(label='Data Download', data=csv_data, file_name=f'stockprice_{datetime.today().year}.csv', mime='text/csv',)
    # 株価推移の折れ線グラフの表示
    st.line_chart(df_1[stocks])

# 前年のボタン
elif button_2:
    st.subheader(f'{datetime.today().year - 1}年の株価推移')
    # 選択モードの選択
    mode = st.selectbox(label="銘柄の選択方法を選んでください", options=select_modes)
    # 選択された銘柄の取得
    stocks = select_mode(mode)
    # CSVデータのエンコード
    csv = df_2[stocks].to_csv().encode('UTF-8')
    # ダウンロードボタンの表示
    st.download_button(label='Data Download', data=csv_data, file_name=f'stockprice_{datetime.today().year - 1}.csv', mime='text/csv',)
    # 株価推移の折れ線グラフの表示
    st.line_chart(df_2[stocks])

# 2年前のボタン
elif button_3:
    st.subheader(f'{datetime.today().year - 2}年の株価推移')
    # 選択モードの選択
    mode = st.selectbox(label="銘柄の選択方法を選んでください", options=select_modes)
    # 選択された銘柄の取得
    stocks = select_mode(mode)
    # CSVデータのエンコード
    csv_data = df_3[stocks].to_csv().encode('UTF-8')
    # ダウンロードボタンの表示
    st.download_button(label='Data Download', data=csv_data, file_name=f'stockprice_{datetime.today().year - 2}.csv', mime='text/csv',)
    # 株価推移の折れ線グラフの表示
    st.line_chart(df_3[stocks])

else:
    st.subheader(f'{datetime.today().year}年の株価推移')
    # 選択モードの選択
    mode = st.selectbox(label="銘柄の選択方法を選んでください", options=select_modes)
    # 選択された銘柄の取得
    stocks = select_mode(mode)
    # CSVデータのエンコード
    csv_data = df_1[stocks].to_csv().encode('UTF-8')
    # ダウンロードボタンの表示
    st.download_button(label='Data Download', data=csv_data, file_name=f'stockprice_{datetime.today().year}.csv', mime='text/csv',)
    # 株価推移の折れ線グラフの表示
    st.line_chart(df_1[stocks])

Overwriting sample9.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample9.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample9.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

## ウィジェットの表示②

参考ページ：[こちら](https://data-analytics.fun/2022/06/26/streamlit-widget-2/)  
公式ページ：[こちら](https://docs.streamlit.io/library/api-reference/widgets)

- `st.slider()` ：スライダーを作成
  - `label`プロパティ：スライダーの上部に表示するテキスト
  - `min_value`プロパティ：選択できる最小の値。
  - `max_value`プロパティ：選択できる最大の値。
  - `step`プロパティ：選択できる値の間隔。  
   　　　　　　　　  デフォルトはint型の場合1、float型の場合0.01、日付の場合は1日。
  - `format`プロパティ：日付などのフォーマットを指定。
``` python
# スライダーを表示し、ユーザーが月を選択する
month = st.slider(label="月を選択してください",
        min_value=1,
        max_value=12,
        step=1,
        format='%d月',
    )
```
![](https://imgur.com/f8qPwEZ.png)
``` python
# スライダーを表示し、ユーザーが期間を選択する
last_year = datetime.today().year - 1
dates = st.slider(label="スライダー",
        min_value=datetime(last_year, 1, 1),
        max_value=datetime(last_year, 12, 31),
        value=(datetime(last_year, 1, 1), datetime(last_year, 12, 31))
)
```
![](https://imgur.com/7bCl9aP.png)

- `st.number_input()` ：数字を入力するウィジェットを作成
  - `label`：スライダーの上部に表示するテキスト。
  - `min_value`：選択できる最小の値。
  - `max_value`：選択できる最大の値。
  - `value`：デフォルトで表示する値。
  - `step`：選択できる値の間隔。  
  　　　  デフォルトはint型の場合1、float型の場合0.01、日付の場合は1日。
  - `format`：日付などのフォーマットを指定。
``` python
# 数値入力フィールドを表示し、ユーザーが月を入力する
month = st.number_input(
    label="月を選択してください",
    min_value = 1,
    max_value = 12,
    value = 1,
)
```
![](https://imgur.com/1QRhIb4.png)

- `st.text_input()` ：テキストを入力するウィジェットを作成（一行）
  - `label`：スライダーの上部に表示するテキスト。
  - `value`： デフォルトで表示されるテキスト。
``` python
# テキスト入力フィールドを表示し、ユーザーがコメントを入力する
text = st.text_input(
        label="コメントを入力してください",
        value="コメント未入力"
    )
# 入力されたコメントを表示する
st.write(f"st.text_input()の入力内容\n\n{text}", unsafe_allow_html=True)
```
![](https://imgur.com/ad1svfv.png)

- `st.text_area()` ：テキストを入力するウィジェットを作成（複数行）
  - `label`：スライダーの上部に表示するテキスト。
  - `value`： デフォルトで表示されるテキスト。
  - `height`：高さをピクセル単位で指定。
  - `width`： 幅をピクセル単位で指定。
``` python
# 長いテキスト入力フィールドを表示し、ユーザーが長いコメントを入力する
long_text = st.text_area(
        label="コメントを入力してください",
        value="コメント未入力",
        height=200
    )
# 入力された長いコメントを表示する
st.write(f"st.text_area()の入力内容\n\n{long_text}", unsafe_allow_html=True)
```
![](https://imgur.com/9Swfjla.png)

- `st.date_input()` ：表示されるカレンダーをもとに日付を指定
  - `label`：スライダーの上部に表示するテキスト。
  - `min_value`：選択できる最小の値。
  - `max_value`：選択できる最大の値。
  - `value`：デフォルトで選択される日付。
``` python
# 日付を選択する入力ウィジェットを表示し、ユーザーが日付を選択する
last_year = datetime.today().year - 1
date = st.date_input(
        label="日付を選択してください",
        value=datetime(last_year, 1, 1),
        min_value=datetime(last_year, 1, 1),
        max_value=datetime(last_year, 12, 31),
)
```
![](https://imgur.com/JwAh6bp.png)
``` python
# 日付入力フィールドを表示し、ユーザーが期間を入力する
last_year = datetime.today().year - 1
dates = st.date_input(
        label="期間を選択してください",
        value=(datetime(last_year, 1, 1), datetime(last_year, 12, 31)),
        min_value=datetime(last_year, 1, 1),
        max_value=datetime(last_year, 12, 31),
)
```
![](https://imgur.com/9TUAJVa.png)

- `st.file_uploader()` ：ファイルのアップローダーを作成
  - `label`：ファイルアップローダの上に表示するラベル。
  - `type`：受け付ける拡張子。
  - `accept_multiple_files`：複数ファイルの選択を許容するかどうか。
``` python
# ファイルアップロード
files = st.file_uploader(
    label='ファイルをアップロードしてください',
    accept_multiple_files=True,
)
# アップロードされたファイル名を表示する
if files is not None:
    filenames = [file.name for file in files]
    st.write("アップロードされたファイル名：", ", ".join(filenames))
```
![](https://imgur.com/DhzehPi.png)

In [ ]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 株価情報の取得（現在年の一年前）
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]  # Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
start_date = f"{datetime.today().year - 1}-12-01"  # 取得開始日
end_date = f"{datetime.today().year - 2}-12-31"  # 取得終了日
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# 月ごとのリターンを計算
df_monthly = df.resample('M').last().pct_change()
df_monthly = df_monthly.dropna()

# インデックスの変更
months = [f"{i}月" for i in range(1, 13)]
df_monthly.index = months
df_monthly

[*********************100%%**********************]  5 of 5 completed

       Google     Apple  Facebook    Amazon  Microsoft
1月   0.120254  0.110521  0.237909  0.227738   0.033317
2月  -0.088830  0.021623  0.174330 -0.086299   0.006497
3月   0.151788  0.118649  0.211501  0.096148   0.155882
4月   0.034802  0.028987  0.133906  0.020912   0.065765
5月   0.144681  0.044613  0.101531  0.143480   0.068769
6月  -0.025800  0.094330  0.084089  0.081108   0.036999
7月   0.108772  0.012785  0.110182  0.025468  -0.013567
8月   0.025995 -0.043675 -0.071281  0.032391  -0.024292
9月  -0.038995 -0.088678  0.014600 -0.078907  -0.036643
10月 -0.051811 -0.002570  0.003531  0.046963   0.070815
11月  0.068101  0.112315  0.085903  0.097678   0.120671
12月  0.054026  0.013583  0.081950  0.040044  -0.007574

In [ ]:
#@title ウィジェットの表示②
# sample10.pyというファイルに記述する

%%writefile sample10.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 現在年の二年前の12月1日を取得
start_date = datetime(datetime.today().year - 2, 12, 1).strftime('%Y-%m-%d')
# 現在年の一年前の12月31日を取得
end_date = datetime(datetime.today().year - 1, 12, 31).strftime('%Y-%m-%d')

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# 日ごとのリターンを計算
df_returns = df.pct_change().dropna()

# 月ごとのリターンを計算
df_monthly = df.resample('M').last().pct_change()
df_monthly = df_monthly.dropna()

# インデックスの変更
months = [f"{i}月" for i in range(1, 13)]
df_monthly.index = months

# 選択肢のリスト
infos = ["ある日の株価リターン", "月の株価リターン", "株価推移"]
# 選択ボックスを表示し、ユーザーが情報を選択する
info = st.selectbox(label="取得したい情報を選んでください", options=infos)

# ある日の株価リターンの選択
if info=="ある日の株価リターン":
    # 前年の日付を取得
    last_year = datetime.today().year - 1
    # 日付を選択する入力ウィジェットを表示し、ユーザーが日付を選択する
    date = st.date_input(
            label="日付を選択してください",
            value=datetime(last_year, 1, 1),
            min_value=datetime(last_year, 1, 1),
            max_value=datetime(last_year, 12, 31),
                )

    # 選択された日付を文字列に変換
    str_date = date.strftime('%Y-%m-%d')
    # 日付がデータフレームのインデックスにあるかどうかをチェックし、適切な処理を行う
    if str_date in df.index:
        # 日付の株価リターンをサブヘッダーとして表示し、棒グラフで表示する
        st.subheader(f'{date.strftime("%Y年%m月%d日")}のリターン')
        st.bar_chart(df_returns.loc[str_date])
    else:
        # 日付の株価リターンがないことを表示する
        st.subheader(f'{date.strftime("%Y年%m月%d日")}のリターンはありません')

# 月の株価リターンの選択
elif info=="月の株価リターン":
    # 選択方法のリスト
    modes = ["Slider", "Number Input"]
    # 選択方法を選択するラジオボタンを表示し、ユーザーが選択する
    mode = st.radio(label='月の選択方法を選んでください', options=modes, index=0, horizontal=True)
    if mode=="Slider":
        # スライダーを表示し、ユーザーが月を選択する
        month = st.slider(label="月を選択してください",
            min_value=1,
            max_value=12,
            step=1,
            format='%d月',
        )
    elif mode=="Number Input":
        # 数値入力フィールドを表示し、ユーザーが月を入力する
        month = st.number_input(
            label="月を選択してください",
            min_value = 1,
            max_value = 12,
            value = 1,
        )
    # 選択された月の株価リターンを表示するサブヘッダーを作成し、棒グラフで表示する
    st.subheader(f'{datetime.today().year - 1}年{month}月')
    st.bar_chart(df_monthly.loc[f"{month}月"])

# 株価推移の選択
elif info=="株価推移":
    # 選択方法のリスト
    modes = ["Slider", "Date Input"]
    # 選択方法を選択するラジオボタンを表示し、ユーザーが選択する
    mode = st.radio(label='日付の選択方法を選んでください', options=modes, index=0, horizontal=True)
    if mode=="Slider":
        # スライダーを表示し、ユーザーが期間を選択する
        last_year = datetime.today().year - 1
        dates = st.slider(label="スライダー",
            min_value=datetime(last_year, 1, 1),
            max_value=datetime(last_year, 12, 31),
            value=(datetime(last_year, 1, 1), datetime(last_year, 12, 31))
        )
    elif mode=="Date Input":
        # 日付入力フィールドを表示し、ユーザーが期間を入力する
        last_year = datetime.today().year - 1
        dates = st.date_input(
                label="期間を選択してください",
                value=(datetime(last_year, 1, 1), datetime(last_year, 12, 31)),
                min_value=datetime(last_year, 1, 1),
                max_value=datetime(last_year, 12, 31),
                    )

    # 選択された期間の株価推移を表示する
    if len(dates) == 2:
        date_start, date_end = dates
        start = date_start.strftime('%Y-%m-%d')
        end = date_end.strftime('%Y-%m-%d')
        st.subheader(f'{date_start.strftime("%Y年%m月%d日")}から{date_end.strftime("%Y年%m月%d日")}までの株価推移')
        st.line_chart(df.loc[start: end])

# テキスト入力フィールドを表示し、ユーザーがコメントを入力する
text = st.text_input(
        label="コメントを入力してください",
        value="コメント未入力"
    )
# 入力されたコメントを表示する
st.write(f"st.text_input()の入力内容\n\n{text}", unsafe_allow_html=True)

# 長いテキスト入力フィールドを表示し、ユーザーが長いコメントを入力する
long_text = st.text_area(
        label="コメントを入力してください",
        value="コメント未入力",
        height=200
    )
# 入力された長いコメントを表示する
st.write(f"st.text_area()の入力内容\n\n{long_text}", unsafe_allow_html=True)

# ファイルアップロード
files = st.file_uploader(
    label='ファイルをアップロードしてください',
    accept_multiple_files=True,
)

# アップロードされたファイル名を表示する
if files is not None:
    filenames = [file.name for file in files]
    st.write("アップロードされたファイル名：", ", ".join(filenames))

Overwriting sample10.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample10.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample10.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

## レイアウト設定

参考ページ：[こちら](https://data-analytics.fun/2022/07/04/streamlit-layout/)

- `st.sidebar()` ：サイドバーを作成
  - やり方は以下の2種類ある。
    - `st.sidebar.<メソッド>`
    - `with st.sidebar:`
``` python
# Using "with" notation
with st.sidebar:
          with st.expander("解説を見る"):
              st.write("contents")
```
``` python
# Using object notation
with st.sidebar.expander("解説を見る"):
            st.write("contents")
```
![](https://imgur.com/5ynciTM.png)

- `st.columns()` ：1行に複数列の設定
  - それぞれの列にはインデックスを使用してアクセスする。
  - **整数**を指定：引数で渡された数の分**等間隔**の列を作成する  
`st.columns(2)`とすると、幅が同じ2列が作成される

  - **整数のリスト**を指定：要素の大きさに準する幅で、要素分の列を作成する  
  `st.columns([3,7])`とすると、幅の比が3対7で分割される
``` python
cols = st.columns([3, 7])
cols[0].write("contents")
```
![](https://imgur.com/4chiuei.png)

- `st.tabs()` ：タブの設定
  - 引数にはタブのラベルを含むリストを渡す。
  - それぞれのタブは、インデックスを使用してアクセスされる。
``` python
tabs = tab_area.tabs(["📈 グラフ", "🗃 データ"])
with tabs[0]:
        st.write("contents1")
with tabs[1]:
        st.write("contents2")
```
![](https://imgur.com/NSTaTyA.png)

- `st.expander()` ：エクスパンダーを設定
  - デフォルトは非表示だが、 "+" ボタンを押すことによって開くもの。
``` python
with st.expander("解説を見る"):
        st.subheader("Meta（旧Facebook）社の株価の下落(2月3日)")
        st.write("Meta社の株価が一日で約26％も急落し、これは米企業としては史上最大の減少幅となりました。")
        st.write("その背景には、2021年10～12月期の決算が約2年ぶりの減益となったことなどが挙げられます。")
        st.subheader("Meta社の株価の下落(10月27日)")
        st.write("Meta社の決算発表日であったこの日、Meta社の株価が一日で約20％も急落しました。")
        st.write("CEOがメタバース産業からの撤退を明言しない姿勢を示したことが原因とされています。")
```
![](https://imgur.com/xocsvqV.png)

- `st.container()` ：コンテナの設定
  - 複数のStreamlitコンポーネントをまとめてグループ化できるようになる。
  - コンテナを使用することで、コンポーネントを分類し、視覚的に区別することができる。
``` python
cols = st.columns([3, 7])
with cols[0].container(): # 左の列にコンテナを設定
        st.write("contents1")
        st.write("contents2")
```
![](https://imgur.com/4chiuei.png)

- `st.empty()` ：空のウィジェットの設定
  - 要素を自由に置き換えたり削除することが可能になる。
``` python
tab_area = cols[1].empty()
if len(dates) == 2:
        tabs = tab_area.tabs(["📈 グラフ", "🗃 データ"])
```
![](https://imgur.com/MFVhpoQ.png)

In [ ]:
#@title レイアウト設定
# sample11.pyというファイルに記述する

%%writefile sample11.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# 株価情報の取得
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]  # Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
start_date = "2021-12-31"  # 取得開始日
end_date = "2022-12-31"  # 取得終了日

price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

cols = st.columns([3, 7])
with cols[0].container(): # 左の列にコンテナを設定
    # 銘柄と期間の選択
    stocks = st.multiselect(label="銘柄を選んでください",
                options=df.columns,
                default=["Google", "Apple"]
    )

    dates = st.date_input(
            label="期間を選択してください",
            value=(datetime(2022, 1, 1), datetime(2022, 12, 31)),
            min_value=datetime(2022, 1, 1),
            max_value=datetime(2022, 12, 31),
                )

tab_area = cols[1].empty()

# 期間が選択された場合の処理
if len(dates) == 2:
    start_date, end_date = dates
    str_start_date = start_date.strftime('%Y-%m-%d')
    str_end_date = end_date.strftime('%Y-%m-%d')

    # タブの作成
    tabs = tab_area.tabs(["📈 グラフ", "🗃 データ"])

    # グラフとデータの表示
    with tabs[0]:
        # サブヘッダーとして選択された期間を表示
        st.subheader(f'{start_date.strftime("%Y年%m月%d日")}から{end_date.strftime("%Y年%m月%d日")}までの株価推移')

        # 線グラフを表示
        st.line_chart(df.loc[str_start_date: str_end_date][stocks])

    with tabs[1]:
        # サブヘッダーとして選択された期間を表示
        st.subheader(f'{start_date.strftime("%Y年%m月%d日")}から{end_date.strftime("%Y年%m月%d日")}までの株価推移')

        # データフレームをCSV形式に変換して、UTF-8でエンコード
        csv_data = df.loc[str_start_date: str_end_date][stocks].to_csv().encode('UTF-8')

        # CSVファイルをダウンロードするボタンを作成
        st.download_button(
            label='Data Download',  # ボタンのラベル
            data=csv_data,  # ダウンロードするデータ
            file_name=f'stockprice_{datetime.today().year}.csv',  # ダウンロードされるファイルの名前
            mime='text/csv',  # MIMEタイプ
        )

        # ダウンロードするデータのプレビューとしてデータフレームを表示
        st.write(df.loc[str_start_date: str_end_date][stocks])


# サイドバーに解説を表示
with st.sidebar:
    with st.expander("解説を見る"):
        st.subheader("Meta（旧Facebook）社の株価の下落(2月3日)")
        st.write("Meta社の株価が一日で約26％も急落し、これは米企業としては史上最大の減少幅となりました。")
        st.write("その背景には、2021年10～12月期の決算が約2年ぶりの減益となったことなどが挙げられます。")
        st.subheader("Meta社の株価の下落(10月27日)")
        st.write("Meta社の決算発表日であったこの日、Meta社の株価が一日で約20％も急落しました。")
        st.write("CEOがメタバース産業からの撤退を明言しない姿勢を示したことが原因とされています。")

Overwriting sample11.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample11.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample11.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

## フォーム設定

参考ページ：[こちら](https://data-analytics.fun/2022/07/09/streamlit-form/)

- `st.form()` ：フォームを作成するための機能
  - フォーム全体が一つのコンテナとして扱われる。
  - 実際にフォーム部分が線で囲まれる。
  - `clear_on_submit`：`True`にするとボタンを押したときに値がクリアされる

  - `st.form_submit_button()` ：送信ボタン
    - フォームの内容を一括で渡すsubmitボタン
    - **フォーム内で`st.form_submit_button()`がないとエラーになる**。

  ＜メリット＞
  - submitボタンが押されるまでの入力内容を保持できる
  - 必須項目のバリデーション、入力内容の確認画面の生成などを実装できる
  - フォームの要素を独自のスタイルでレイアウトすることができる

  ``` python
  # フォームの開始
  with st.form("my_form"):
      name = st.text_input("名前を入力してください")
      birthday = st.date_input(
          label="誕生日を選択してください",
          value=datetime(2003, 1, 1),
          min_value=datetime(1900, 1, 1),
          max_value=datetime(2022, 12, 31),
      )
      submit_btn = st.form_submit_button("送信")
  ```
![](https://imgur.com/Vzamh4Y.png)

In [ ]:
#@title フォーム設定
%%writefile sample12.py
import streamlit as st
from datetime import datetime, timedelta, date

st.title("次の誕生日までの日数計算")
st.caption("次の誕生日までの残り日数を計算します")

# ラジオボタンでフォームを選択する
modes = ["`st.form()`未使用時", "`st.form()`使用時"]
mode = st.radio(label='選択してください', options=modes, index=0, horizontal=True)

if mode == "`st.form()`未使用時":
    # ユーザー入力の受け取り
    name = st.text_input("名前を入力してください")
    birthday = st.date_input(
        label="誕生日を選択してください",
        value=datetime(2003, 1, 1),
        min_value=datetime(1900, 1, 1),
        max_value=datetime(2022, 12, 31),
    )
    today = date.today()

    # 現在の年齢を計算
    age = today.year - birthday.year - ((today.month, today.day) < (birthday.month, birthday.day))

    # 次の誕生日の日付を計算
    next_birthday_year = today.year if today.month < birthday.month or (today.month == birthday.month and today.day <= birthday.day) else today.year + 1
    next_birthday = date(next_birthday_year, birthday.month, birthday.day)

    # 現在日付との日数の差を計算
    days_to_next_birthday = (next_birthday - today).days

    # ボタンの設置
    submit_btn = st.button("送信")
    cancel_btn = st.button("キャンセル")

else:
    # フォームの開始
    with st.form("my_form"):
        name = st.text_input("名前を入力してください")
        birthday = st.date_input(
            label="誕生日を選択してください",
            value=datetime(2003, 1, 1),
            min_value=datetime(1900, 1, 1),
            max_value=datetime(2022, 12, 31),
        )
        today = date.today()

        # 現在の年齢を計算
        age = today.year - birthday.year - ((today.month, today.day) < (birthday.month, birthday.day))

        # 次の誕生日の日付を計算
        next_birthday_year = today.year if today.month < birthday.month or (today.month == birthday.month and today.day <= birthday.day) else today.year + 1
        next_birthday = date(next_birthday_year, birthday.month, birthday.day)

        # 現在日付との日数の差を計算
        days_to_next_birthday = (next_birthday - today).days

        # submitボタンの生成
        submit_btn = st.form_submit_button("送信")
        # フォームの中に新たなボタンは置けない
        # cancel_btn = st.button("キャンセル")

# 結果の出力
if submit_btn:
    st.write(f"{name}さんは現在、{age}歳です。")
    st.write(f"{name}さんの次の誕生日まで、あと{days_to_next_birthday}日です。")

Overwriting sample12.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample12.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample12.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

## 状態の保持とコールバック

Streamlitは、ウィジェットの値や状態が変化すると、
すべての処理が1から再度実行されます。

そのため、ウィジェットの状態を記憶するために、
**状態を保持する方法**を学ぶ必要があります。

またその際に、**コールバック**という機能を使えると便利です。

参考ページ：[こちら](https://data-analytics.fun/2022/07/11/streamlit-state-callback/)

- `st.session_state` ：状態を保持する辞書型の変数
  - 使用することで、値を保持したり、保持された値を取りだしたりすることができる。
  - ページがリロードされるまでクリアされない。
``` python
# `st.session_state`を使用する場合
if mode == "`st.session_state`使用時":
    value = 0
    st.subheader(f'初期値は{value}です。')
    btn = st.button('+1する')
    # セッション状態にキーが存在しない場合、初期化する
    if 'increment' not in st.session_state:
        st.session_state['increment'] = 0

    if btn:
        st.session_state['increment'] += 1 # 値を増やす
        st.write(f"{st.session_state['increment']}になりました。")
```
![](https://imgur.com/8mGioyX.png)

- コールバック関数 ：ボタンがクリックされたとき、ウィジェットの値が変わったときに呼び出される関数
  - クリックされたとき、値が変わったときに、 真っ先に指定した関数が呼び出される。
  - 引数は、ボタンの場合は**`on_click`**、
ンプットボックスやセレクトボックス(ドロップダウン)の場合は**`on_change`**を設定する。
  - ウィジェットの前にコールバック関数を書いておき、
  `on_click`の引数として作成したコールバック関数名を指定する。

  ``` python
  # コールバック関数を使わない例
  # ボタンクリック→テーブル表示（5件）→表示数の変数更新
  # →ボタンクリック→テーブル表示（10件）

  # 初期表示のデータ数を設定
  if 'num_of_data' not in st.session_state.keys():
      st.session_state['num_of_data'] = 5

  # テーブルを表示し、ボタンを表示
  st.table(df.head(st.session_state['num_of_data']))  # 初期表示は5件
  btn = st.button('さらに見る')  # ボタンをクリックするとデータ数が更新される
  if btn:
      st.session_state['num_of_data'] += 5  # 更新されたデータ数でテーブルを再表示

  ```
  ``` python
  # コールバック関数を使う例
  # ボタンクリック→表示数の変数更新→テーブル表示（10件）
  # →ボタンクリック→テーブル表示（15件）

  # 初期表示のデータ数を設定
  if 'num_of_data' not in st.session_state.keys():
      st.session_state['num_of_data'] = 5

  # コールバック関数: データ数を更新する
  def update_num_of_data():
      st.session_state['num_of_data'] += 5

  # テーブルを表示し、ボタンを表示
  st.table(df.head(st.session_state['num_of_data']))  # 初期表示は5件
  btn = st.button('さらに見る', on_click=update_num_of_data)  # ボタンをクリックするとデータ数が更新される
  if btn:
      st.table(df.head(st.session_state['num_of_data']))  # 更新されたデータ数でテーブルを再表示
  ```


![](https://imgur.com/p55cfm6.png)

In [ ]:
#@title 状態の保持
# sample13.pyというファイルに記述する

%%writefile sample13.py
import streamlit as st

# ラジオボタンでフォームを選択する
modes = ["`st.session_state`未使用時", "`st.session_state`使用時"]
mode = st.radio(label='選択してください', options=modes, index=0, horizontal=True)

# `st.session_state`を使用する場合
if mode == "`st.session_state`使用時":
    value = 0
    st.subheader(f'初期値は{value}です。')
    btn = st.button('+1する')
    # セッション状態にキーが存在しない場合、初期化する
    if 'increment' not in st.session_state:
        st.session_state['increment'] = 0

    if btn:
        st.session_state['increment'] += 1 # 値を増やす
        st.write(f"{st.session_state['increment']}になりました。")

# `st.session_state`を使用しない場合
else:
    value = 0
    st.subheader(f'初期値は{value}です。')
    btn = st.button('+1する')
    if btn:
        value += 1
        st.write(f'{value}になりました。')

Overwriting sample13.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample13.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample13.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

In [ ]:
#@title コールバック関数
# sample14.pyというファイルに記述する

%%writefile sample14.py
import streamlit as st
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

# Google、Apple、Facebook、Amazon, Microsoftの銘柄コード
tickers = ["GOOGL", "AAPL", "META", "AMZN", "MSFT"]
# 株価情報の取得
start_date = (datetime.today() + timedelta(hours=9) - timedelta(days=365)).strftime('%Y-%m-%d')  # 取得開始日
end_date = (datetime.today() + timedelta(hours=9)).strftime('%Y-%m-%d')  # 取得終了日
price_data = yf.download(tickers, start=start_date, end=end_date)["Close"]

# データフレームの作成
df = pd.DataFrame({
    "Google": price_data[tickers[0]],
    "Apple": price_data[tickers[1]],
    "Facebook": price_data[tickers[2]],
    "Amazon": price_data[tickers[3]],
    "Microsoft": price_data[tickers[4]]
})

# 初期表示のデータ数を設定
if 'num_of_data' not in st.session_state:
    st.session_state['num_of_data'] = 5

# コールバック関数
def update_num_of_data():
    st.session_state['num_of_data'] += 5

# 2023年の株価推移（線グラフ）
st.header('一年間の株価推移')
st.line_chart(df)

with st.expander('データを見る'):
    # テーブルを表示し、ボタンを表示
    st.table(df.head(st.session_state['num_of_data']))  # 初期表示は5件
    btn = st.button('さらに見る', on_click=update_num_of_data)  # ボタンをクリックするとデータ数が更新される

Overwriting sample14.py

In [ ]:
# 現在のグローバルIPを取得して表示する
print('your globalip: ' + requests.get('https://ifconfig.me').text)

# Streamlitアプリを実行し、3秒待機してからローカルトンネルを作成する
# sample14.pyというpythonファイルを実行
# ドメインは"sample"を指定
!streamlit run sample14.py & sleep 3 && npx localtunnel --port 8501 --subdomain "sample"

## その他

Streamlitの機能について、他のものも以下に紹介します。

①[ステータスの表示](https://data-analytics.fun/2022/07/06/streamlit-display-status/)

→ プログレスバー・スピナー・メッセージボックス・風船 など

②[テーマ変更とページの設定](https://data-analytics.fun/2022/07/10/streamlit-theme-page-settings/)

→ 表示幅の変更・ファビコンの設定 など

③[君には今から3時間で機械学習Webアプリを作ってもらうよ](https://zenn.dev/alivelimb/articles/20220528-streamlit-ml-app)

→ Streamlitを紹介している、大バズリした記事。

④[Streamlit 覚書](https://qiita.com/not13/items/dcd8c12d64982dc0e819)

→ Streamlitの文法をかなり網羅している。

## デプロイ方法

サーバー上に配置することで、Streamlitで作ったアプリが  
だれでも利用できる状態になります。

参考ページ：[こちら](https://camp.trainocate.co.jp/magazine/streamlit-web/)

### 1.Streamlit Cloudにサインイン

Streamlit Cloudは、Streamlitで作成したWebアプリを簡単にデプロイできるサービスです。

以下のリンクにアクセスします。

https://share.streamlit.io/signup

![](https://imgur.com/IZYVQc4.png)

Googleアカウント、Githubアカウント、メールアドレスのいずれかを利用してアカウントを作成します。

### 2.Githubアカウント連携

`Connect Github account`をクリックして、Githubアカウントと連携します。

![](https://imgur.com/GjDihUe.png)

### 3.pyファイルのアップロード

pythonプログラムをGithubリポジトリにアップロードします。  
今回は"Streamlit"というフォルダにpyファイルを入れます。

![](https://imgur.com/C69xNST.png)

Github上の操作でpyファイルをアップロードします。

![](https://imgur.com/XuD2xMZ.png)
![](https://imgur.com/oUjg8nd.png)

### 4. リポジトリ・ブランチ・ファイルパスを選択

Streamlit cloudの管理画面の右上にある"New app"を選択します。

![](https://imgur.com/lxo5Odt.png)

リポジトリ、ブランチ、実行ファイル名を入力します。

![](https://imgur.com/mLP2Tp0.png)

### 5. デプロイ

必要項目を入力し "Deploy!" をクリックするとデプロイされます。


アプリのデプロイが完了するとURLが発行されます。